name: go

on: [push, pull_request]

jobs:
  build_and_test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true
      - run: go version
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
      - run: go test -v -coverprofile=profile.cov ./...
      - name: build and vet cmd module
        working-directory: cmd
        run: |
          go build -o /dev/null ./generateEmojiCodeMap
          go vet ./...
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov


