name: go

on: [push, pull_request]

jobs:
  build_and_test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go version
      - name: Set up GOPATH
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
          echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"
      - name: setup tools
        run: |
          go install github.com/mattn/goveralls@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - run: golangci-lint run
      - run: go test ./...
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -v -service github

